name = "kv-proxy"
compatibility_date = "2023-05-13"
main = "src/index.ts"
usage_model = "unbound"
workers_dev = false

routes = ["kv.uuid.rocks/*"]

kv_namespaces = [
  { binding = "EEMAILME", id = "c5f446fc4fcf4024a0bca6cdcb4921ed" }
]

[define]
ENVIRONMENT = '"production"'

[[r2_buckets]]
binding = 'EEMAILMEKV'
bucket_name = 'eemailme-kv'
