name = "kv-proxy"
compatibility_date = "2023-05-13"
main = "src/index.ts"
usage_model = "unbound"
workers_dev = false
logpush = true

routes = ["kv.uuid.rocks/*"]

[define]
ENVIRONMENT = '"production"'

[[r2_buckets]]
binding = 'EEMAILMEKV'
bucket_name = 'eemailme-kv'
